openapi: 3.0.4
info:
  title: ATS-Mini - OpenAPI 3.0
  description: |-
    ATS-Mini JSON Api definition for radio control and configuration
  version: 1.0.0
servers:
  - url: http://atsmini.local
  - url: http://10.1.1.1
tags:
  - name: status
    description: Radio status and information
  - name: memory
    description: Memory slot information
  - name: config
    description: Device configuration management
paths:
  /api/status:
    get:
      tags:
        - status
      summary: Get ATS-Mini status
      description: Returns current radio status including frequency, mode, signal strength, and RDS data
      operationId: getStatus
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/memory:
    get:
      tags:
        - memory
      summary: Get ATS-Mini memories
      description: Returns all memory slots. Empty objects represent unused slots.
      operationId: getMemory
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Memory'
                description: Array of memory slots, empty objects for unused slots
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/config:
    get:
      tags:
        - config
      summary: Get ATS-Mini configuration
      description: Returns current device configuration including WiFi, display, and radio settings
      operationId: getConfig
      security:
        - basicAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        '401':
          description: Authentication required
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      tags:
        - config
      summary: Update ATS-Mini configuration
      description: Updates device configuration. Only provided fields will be updated.
      operationId: setConfig
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigUpdate'
      responses:
        '200':
          description: Configuration updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        '400':
          description: Invalid JSON
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '401':
          description: Authentication required
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/configOptions:
    get:
      tags:
        - config
      summary: Get available configuration options
      description: Returns all available options for configuration fields like themes, UTC offsets, etc.
      operationId: getConfigOptions
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigOptions'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  schemas:
    Status:
      type: object
      required:
        - ip
        - ssid
        - mac
        - version
        - band
        - freq
        - mode
        - rssi
        - snr
        - battery
        - step
        - bandwidth
        - agc
        - volume
        - softMuteMaxAttIdx
      properties:
        ip:
          type: string
          description: Current IP address
          example: "10.1.1.1"
        ssid:
          type: string
          description: WiFi SSID or device name in AP mode
          example: "ATS-Mini"
        mac:
          type: string
          description: Device MAC address
          example: "98:A3:16:C1:DA:9C"
        version:
          type: string
          description: Firmware version string
          example: "F/W: v2.28d Jul 27 2025"
        band:
          type: string
          description: Current band
          example: "VHF"
        freq:
          type: number
          description: Current frequency in Hz (includes BFO offset for non-FM modes)
          example: 94200000
        mode:
          type: string
          description: Current modulation mode
          example: "FM"
        rssi:
          type: number
          description: Received signal strength indicator
          example: 44
        snr:
          type: number
          description: Signal-to-noise ratio in dB
          example: 20
        battery:
          type: number
          format: float
          description: Battery voltage in volts
          example: 3.878347
        step:
          type: string
          description: Frequency step size
          example: "100k"
        bandwidth:
          type: string
          description: Current bandwidth setting
          example: "Auto"
        agc:
          type: boolean
          description: Automatic Gain Control status (true when AGC is enabled)
          example: false
        attenuation:
          type: number
          description: Manual attenuation level (only present when AGC is disabled)
          example: 10
        time:
          type: string
          description: Current time in HH:MM format (only present when clock is available)"
          example: "15:49"
        volume:
          type: number
          description: Current volume level
          example: 50
        squelch:
          type: number
          description: Current squelch level (only present when squelch is enabled)"
          example: 7
        softMuteMaxAttIdx:
          type: number
          description: Soft mute maximum attenuation index
          example: 4
        avc:
          type: number
          description: Automatic Volume Control setting (present for SSB and non-FM modes, not present for FM)
          example: 10
        rds:
          type: object
          description: RDS (Radio Data System) information (only present in FM mode)"
          properties:
            piCode:
              type: string
              description: Program Identification code in hexadecimal (only present when available)
              example: "5241"
            stationName:
              type: string
              description: Station name from RDS PS (Program Service) data (only present when available)
              example: " VIRGIN "
            radioText:
              type: string
              example: "In onda MGK con CLICHE'"
              description: Radio text from RDS RT (Radio Text) data (only present when available)
            programInfo:
              type: string
              description: Program type information from RDS PTY (Program Type) data (only present when available)
              example: "Rock Music"

    Memory:
      type: object
      properties:
        id:
          type: integer
          description: Memory slot ID
          example: 0
        freq:
          type: number
          description: Frequency in Hz
          example: 94200000
        band:
          type: string
          description: Band name
          example: "VHF"
        mode:
          type: string
          description: Modulation mode
          example: "FM"
      description: Memory slot data. Empty objects represent unused slots.

    Config:
      type: object
      required:
        - username
        - password
        - wifissid1
        - wifipass1
        - wifissid2
        - wifipass2
        - wifissid3
        - wifipass3
        - brightness
        - calibration
        - utcOffsetIdx
        - rdsModeIdx
        - fmRegionIdx
        - themeIdx
        - uiLayoutIdx
        - zoomMenu
        - scrollDirection
        - sleepModeIdx
      properties:
        username:
          type: string
          description: Web interface login username (empty string means no authentication)
          example: ""
        password:
          type: string
          description: Web interface login password (empty string means no authentication)
          example: ""
        wifissid1:
          type: string
          description: First WiFi network SSID
          example: ""
        wifipass1:
          type: string
          description: First WiFi network password
          example: ""
        wifissid2:
          type: string
          description: Second WiFi network SSID
          example: ""
        wifipass2:
          type: string
          description: Second WiFi network password
          example: ""
        wifissid3:
          type: string
          description: Third WiFi network SSID
          example: ""
        wifipass3:
          type: string
          description: Third WiFi network password
          example: ""
        brightness:
          type: number
          description: Display brightness level
          example: 130
        calibration:
          type: number
          description: Frequency calibration offset for current band
          example: 0
        rdsModeIdx:
          type: number
          description: RDS mode index (references rdsModes array from configOptions)
          example: 6
        utcOffsetIdx:
          type: integer
          description: UTC offset index (references UTCOffsets array from configOptions)
          example: 8
        fmRegionIdx:
          type: number
          description: FM region index (references fmRegions array from configOptions)
          example: 0
        themeIdx:
          type: integer
          description: Theme index (references themes array from configOptions)
          example: 0
        uiLayoutIdx:
          type: number
          example: 1
          description: UI layout index (references uiLayouts array from configOptions)
        zoomMenu:
          type: boolean
          description: Whether menu zoom is enabled
          example: false
        scrollDirection:
          type: integer
          example: 1
          enum: [-1, 1]
          description: Scroll direction (-1 or 1)
        sleepModeIdx:
          type: number
          description: Sleep mode index (references sleepModes array from configOptions)
          example: 0

    ConfigUpdate:
      type: object
      description: Configuration update request. All fields are optional - only provided fields will be updated.
      properties:
        username:
          type: string
          description: Web interface login username
        password:
          type: string
          description: Web interface login password
        wifissid1:
          type: string
          description: First WiFi network SSID
        wifipass1:
          type: string
          description: First WiFi network password
        wifissid2:
          type: string
          description: Second WiFi network SSID
        wifipass2:
          type: string
          description: Second WiFi network password
        wifissid3:
          type: string
          description: Third WiFi network SSID
        wifipass3:
          type: string
          description: Third WiFi network password
        brightness:
          type: number
          description: Display brightness level
        calibration:
          type: number
          description: Frequency calibration offset
        rdsModeIdx:
          type: number
          description: RDS mode index
        utcOffsetIdx:
          type: integer
          description: UTC offset index
        fmRegionIdx:
          type: number
          description: FM region index
        themeIdx:
          type: integer
          description: Theme index
        uiLayoutIdx:
          type: number
          description: UI layout index
        zoomMenu:
          type: boolean
          description: Menu zoom setting
        scrollDirection:
          type: integer
          description: Scroll direction (-1 or 1)
          enum: [-1, 1]
        sleepModeIdx:
          type: number
          description: Sleep mode index

    ConfigOptions:
      type: object
      required:
        - rdsModes
        - UTCOffsets
        - fmRegions
        - themes
        - uiLayouts
        - sleepModes
      properties:
        rdsModes:
          type: array
          description: Available RDS (Radio Data System) mode options
          items:
            type: object
            required:
              - id
              - mode
              - desc
            properties:
              id:
                type: number
                description: RDS mode option index
                example: 3
              mode:
                type: number
                description: Internal RDS mode value/bitmask
                example: 7
              desc:
                type: string
                description: Human-readable RDS mode description
                example: "PS+PI+CT"
        UTCOffsets:
          type: array
          description: Available UTC time zone offsets
          items:
            $ref: '#/components/schemas/UTCOffset'
        fmRegions:
          type: array
          description: Available FM region settings (affects de-emphasis and frequency ranges)
          items:
            type: object
            required:
              - id
              - value
              - desc
            properties:
              id:
                type: number
                description: FM region option index
                example: 0
              value:
                type: number
                description: Internal FM region value
                example: 1
              desc:
                type: string
                description: FM region description
                example: "EU/JP/AU"
        themes:
          type: array
          items:
            $ref: '#/components/schemas/Theme'
          description: Available themes
        uiLayouts:
          type: array
          description: Available UI layout options
          items:
            type: object
            required:
              - id
              - name
            properties:
              id:
                type: number
                description: UI layout index
                example: 0
              name:
                type: string
                description: UI layout name
                example: "Default"
        sleepModes:
          type: array
          description: Available device sleep mode options
          items:
            type: object
            required:
              - id
              - name
            properties:
              id:
                type: number
                description: Sleep mode index
                example: 0
              name:
                type: string
                description: Sleep mode name
                example: "Locked"

    Theme:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          description: Theme index
          example: 0
        name:
          type: string
          description: Theme name
          example: "Default"

    UTCOffset:
      type: object
      required:
        - id
        - offset
        - desc
        - city
      properties:
        id:
          type: integer
          description: UTC offset index
          example: 0
        offset:
          type: integer
          description: UTC offset in quarter hours
          example: -32
        desc:
          type: string
          description: UTC offset description
          example: "UTC-8"
        city:
          type: string
          description: Representative city
          example: "Fairbanks"

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message describing what went wrong
          example: "Invalid JSON"
